### PR TITLE
Incorrect assertion, an unassigned variable is not null, it is undefined

### PR DESCRIPTION
**Pull request by sethdorris**

### CODE REVIEW

**Comment by Roenok** [comment]
Looks good @sethdorris! I'll merge these.

**Comment by sethdorris** [comment]
@Roenok Thanks for the quick turnaround on that merge! I will have another merge request coming soon implementing additional conversation about ES2015 arrow functions, probably around the topic on class3 about the 'this' keyword, as it makes a significant change in the preservation of lexical this.

**Comment by Roenok** [comment]
@sethdorris Can you add a note about browser support for the newer features as well?

**Comment by sethdorris** [comment]
I'll add a note and show them www.caniuse.com

**Pull request merged**
